package com.overseas.portal.config;

import com.overseas.portal.domain.*;
import com.overseas.portal.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.util.*;

@Slf4j
@Component
@RequiredArgsConstructor
public class DataInitializer implements CommandLineRunner {

    private final UserRepository userRepository;
    private final ChurchRepository churchRepository;
    private final FaithProcessRecordRepository faithProcessRecordRepository;
    private final SystemConfigRepository systemConfigRepository;
    private final PasswordEncoder passwordEncoder;

    @Override
    @Transactional
    public void run(String... args) {
        log.info("Checking and initializing default system data...");

        // 1. Initial Admin & Test Users
        if (!userRepository.existsByUsername("admin")) {
            User admin = User.builder()
                    .username("admin")
                    .passwordHash(passwordEncoder.encode("admin123!"))
                    .name("관리자")
                    .role("ROLE_ADMIN")
                    .assignedCountry("전체")
                    .telegramId("@overseas_admin")
                    .telegramChatId("123456789")
                    .isActive(true)
                    .build();
            userRepository.save(admin);
            log.info("Created default admin user: admin / admin123!");
        }

        if (!userRepository.existsByUsername("user")) {
            User user = User.builder()
                    .username("user")
                    .passwordHash(passwordEncoder.encode("user123!"))
                    .name("해외선교부 담당자")
                    .role("ROLE_USER")
                    .assignedCountry("일본")
                    .telegramId("@overseas_user")
                    .telegramChatId("987654321")
                    .isActive(true)
                    .build();
            userRepository.save(user);
            log.info("Created default user: user / user123!");
        }

        // 2. Initial Telegram Config
        if (systemConfigRepository.findByConfigKey("TELEGRAM_BOT_TOKEN").isEmpty()) {
            systemConfigRepository.save(SystemConfig.builder()
                    .configKey("TELEGRAM_BOT_TOKEN")
                    .configValue("7894561230:AAExampleTokenForOverseasPortal")
                    .description("텔레그램 OTP 발송용 봇 API 토큰")
                    .build());
        }

        // 3. Seed All 21 Churches and 42 Faith Records from data.js into PostgreSQL DB if count < 21
        if (churchRepository.count() < 21) {
            log.info("Seeding all 21 churches and 42 faith process records from data.js into PostgreSQL overseas database...");
            try {
                faithProcessRecordRepository.deleteAllInBatch();
                churchRepository.deleteAllInBatch();
            } catch (Exception e) {
                log.warn("Clearing existing church data: {}", e.getMessage());
            }

            Map<String, Church> churchMap = new HashMap<>();
            Church church_0 = Church.builder()
                    .continent("아시아")
                    .country("일본")
                    .jipa("맛디아")
                    .gubun("교회")
                    .name("도쿄교회")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("35.6812546"))
                    .lon(new BigDecimal("139.766706"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_0);
            churchMap.put("도쿄교회", church_0);
            Church church_1 = Church.builder()
                    .continent("북아메리카")
                    .country("미국")
                    .jipa("맛디아")
                    .gubun("교회")
                    .name("텍사스교회")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("31.2638905"))
                    .lon(new BigDecimal("-98.5456116"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_1);
            churchMap.put("텍사스교회", church_1);
            Church church_2 = Church.builder()
                    .continent("유럽")
                    .country("튀르키예")
                    .jipa("맛디아")
                    .gubun("교회")
                    .name("튀르키예교회")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("41.006381"))
                    .lon(new BigDecimal("28.9758715"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_2);
            churchMap.put("튀르키예교회", church_2);
            Church church_3 = Church.builder()
                    .continent("아시아")
                    .country("파키스탄")
                    .jipa("맛디아")
                    .gubun("교회")
                    .name("파키스탄교회")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("31.5656822"))
                    .lon(new BigDecimal("74.3141829"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_3);
            churchMap.put("파키스탄교회", church_3);
            Church church_4 = Church.builder()
                    .continent("아시아")
                    .country("인도")
                    .jipa("맛디아")
                    .gubun("교회")
                    .name("인도첸나이교회")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("13.0836939"))
                    .lon(new BigDecimal("80.270186"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_4);
            churchMap.put("인도첸나이교회", church_4);
            Church church_5 = Church.builder()
                    .continent("아프리카")
                    .country("콩고민주공화국")
                    .jipa("맛디아")
                    .gubun("교회")
                    .name("콩고민주공화국킨샤사교회")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("-4.32171"))
                    .lon(new BigDecimal("15.3122511"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_5);
            churchMap.put("콩고민주공화국킨샤사교회", church_5);
            Church church_6 = Church.builder()
                    .continent("아시아")
                    .country("카자흐스탄")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("대전교회카자흐스탄아스타나지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("51.1159933"))
                    .lon(new BigDecimal("71.4677059"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_6);
            churchMap.put("대전교회카자흐스탄아스타나지역", church_6);
            Church church_7 = Church.builder()
                    .continent("유럽")
                    .country("포르투갈")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("대전교회포르투갈리스본지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("38.7077507"))
                    .lon(new BigDecimal("-9.1365919"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_7);
            churchMap.put("대전교회포르투갈리스본지역", church_7);
            Church church_8 = Church.builder()
                    .continent("중앙아메리카")
                    .country("멕시코")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("천안교회멕시코과달라하라지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("20.6720375"))
                    .lon(new BigDecimal("-103.338396"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_8);
            churchMap.put("천안교회멕시코과달라하라지역", church_8);
            Church church_9 = Church.builder()
                    .continent("남아메리카")
                    .country("브라질")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("청주교회브라질리우데자네이루지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("-22.9110137"))
                    .lon(new BigDecimal("-43.2093727"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_9);
            churchMap.put("청주교회브라질리우데자네이루지역", church_9);
            Church church_10 = Church.builder()
                    .continent("아시아")
                    .country("인도네시아")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("인도첸나이교회인도네시아마카사르지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("-5.1342962"))
                    .lon(new BigDecimal("119.4124282"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_10);
            churchMap.put("인도첸나이교회인도네시아마카사르지역", church_10);
            Church church_11 = Church.builder()
                    .continent("")
                    .country("")
                    .jipa("맛디아")
                    .gubun("개척지")
                    .name("대전교회해외개척지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("35.6812546"))
                    .lon(new BigDecimal("139.766706"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_11);
            churchMap.put("대전교회해외개척지역", church_11);
            Church church_12 = Church.builder()
                    .continent("")
                    .country("")
                    .jipa("맛디아")
                    .gubun("개척지")
                    .name("청주교회해외개척지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("35.6812546"))
                    .lon(new BigDecimal("139.766706"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_12);
            churchMap.put("청주교회해외개척지역", church_12);
            Church church_13 = Church.builder()
                    .continent("")
                    .country("")
                    .jipa("맛디아")
                    .gubun("개척지")
                    .name("텍사스교회해외개척지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("35.6812546"))
                    .lon(new BigDecimal("139.766706"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_13);
            churchMap.put("텍사스교회해외개척지역", church_13);
            Church church_14 = Church.builder()
                    .continent("")
                    .country("")
                    .jipa("맛디아")
                    .gubun("개척지")
                    .name("인도첸나이교회해외개척지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("35.6812546"))
                    .lon(new BigDecimal("139.766706"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_14);
            churchMap.put("인도첸나이교회해외개척지역", church_14);
            Church church_15 = Church.builder()
                    .continent("아시아")
                    .country("인도")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("인도첸나이인도하이데라바드지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("17.385"))
                    .lon(new BigDecimal("78.4867"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_15);
            churchMap.put("인도첸나이인도하이데라바드지역", church_15);
            Church church_16 = Church.builder()
                    .continent("아시아")
                    .country("인도")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("인도첸나이인도뭄바이지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("19.076"))
                    .lon(new BigDecimal("72.8777"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_16);
            churchMap.put("인도첸나이인도뭄바이지역", church_16);
            Church church_17 = Church.builder()
                    .continent("아시아")
                    .country("인도")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("인도첸나이인도오디샤지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("20.2961"))
                    .lon(new BigDecimal("85.8245"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_17);
            churchMap.put("인도첸나이인도오디샤지역", church_17);
            Church church_18 = Church.builder()
                    .continent("아시아")
                    .country("인도")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("인도첸나이인도카르나타카서부지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("12.9141"))
                    .lon(new BigDecimal("74.856"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_18);
            churchMap.put("인도첸나이인도카르나타카서부지역", church_18);
            Church church_19 = Church.builder()
                    .continent("아프리카")
                    .country("카메룬")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("텍사스교회부에아지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("4.1567895"))
                    .lon(new BigDecimal("9.2315915"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_19);
            churchMap.put("텍사스교회부에아지역", church_19);
            Church church_20 = Church.builder()
                    .continent("아시아")
                    .country("인도네시아")
                    .jipa("맛디아")
                    .gubun("지역")
                    .name("인도첸나이교회인도네시아쿠팡지역")
                    .leaderName("담임사역자")
                    .flightTime("6.3시간")
                    .distanceKm(4760)
                    .timeDiff("한국보다 4시간 느림")
                    .language("현지어·영어")
                    .religion("기독교·이슬람교")
                    .lat(new BigDecimal("-10.1632209"))
                    .lon(new BigDecimal("123.6017755"))
                    .isActive(true)
                    .build();
            churchRepository.save(church_20);
            churchMap.put("인도첸나이교회인도네시아쿠팡지역", church_20);

            FaithProcessRecord r0 = FaithProcessRecord.builder()
                    .church(churchMap.get("도쿄교회"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(7)
                    .bibleCumReg(7)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r0);

            FaithProcessRecord r1 = FaithProcessRecord.builder()
                    .church(churchMap.get("텍사스교회"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(17)
                    .centerMonthOff(0)
                    .centerMonthTotal(17)
                    .centerCumOn(17)
                    .centerCumOff(0)
                    .centerCumReg(17)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r1);

            FaithProcessRecord r2 = FaithProcessRecord.builder()
                    .church(churchMap.get("튀르키예교회"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(70)
                    .centerMonthTotal(70)
                    .centerCumOn(0)
                    .centerCumOff(70)
                    .centerCumReg(70)
                    .centerMonthGrad(20)
                    .centerTotMonthReg(78)
                    .centerCumGrad(20)
                    .centerAttElem(75)
                    .centerAttMid(75)
                    .centerAttHigh(28)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(20)
                    .cumNewAdmit(20)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r2);

            FaithProcessRecord r3 = FaithProcessRecord.builder()
                    .church(churchMap.get("파키스탄교회"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(47)
                    .bibleCumReg(47)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(78)
                    .centerMonthTotal(78)
                    .centerCumOn(0)
                    .centerCumOff(78)
                    .centerCumReg(78)
                    .centerMonthGrad(64)
                    .centerTotMonthReg(191)
                    .centerCumGrad(64)
                    .centerAttElem(191)
                    .centerAttMid(191)
                    .centerAttHigh(181)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(64)
                    .cumNewAdmit(64)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r3);

            FaithProcessRecord r4 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이교회"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(185)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r4);

            FaithProcessRecord r5 = FaithProcessRecord.builder()
                    .church(churchMap.get("콩고민주공화국킨샤사교회"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(140)
                    .bibleCumReg(140)
                    .bibleCurAtt(67)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r5);

            FaithProcessRecord r6 = FaithProcessRecord.builder()
                    .church(churchMap.get("대전교회카자흐스탄아스타나지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(6)
                    .centerMonthTotal(6)
                    .centerCumOn(0)
                    .centerCumOff(6)
                    .centerCumReg(6)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r6);

            FaithProcessRecord r7 = FaithProcessRecord.builder()
                    .church(churchMap.get("대전교회포르투갈리스본지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(10)
                    .bibleCumReg(10)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r7);

            FaithProcessRecord r8 = FaithProcessRecord.builder()
                    .church(churchMap.get("천안교회멕시코과달라하라지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r8);

            FaithProcessRecord r9 = FaithProcessRecord.builder()
                    .church(churchMap.get("청주교회브라질리우데자네이루지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r9);

            FaithProcessRecord r10 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이교회인도네시아마카사르지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r10);

            FaithProcessRecord r11 = FaithProcessRecord.builder()
                    .church(churchMap.get("대전교회해외개척지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(27)
                    .centerMonthTotal(27)
                    .centerCumOn(0)
                    .centerCumOff(27)
                    .centerCumReg(27)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r11);

            FaithProcessRecord r12 = FaithProcessRecord.builder()
                    .church(churchMap.get("청주교회해외개척지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r12);

            FaithProcessRecord r13 = FaithProcessRecord.builder()
                    .church(churchMap.get("텍사스교회해외개척지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r13);

            FaithProcessRecord r14 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이교회해외개척지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r14);

            FaithProcessRecord r15 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이인도하이데라바드지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r15);

            FaithProcessRecord r16 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이인도뭄바이지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r16);

            FaithProcessRecord r17 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이인도오디샤지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r17);

            FaithProcessRecord r18 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이인도카르나타카서부지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r18);

            FaithProcessRecord r19 = FaithProcessRecord.builder()
                    .church(churchMap.get("텍사스교회부에아지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r19);

            FaithProcessRecord r20 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이교회인도네시아쿠팡지역"))
                    .yearMonth("2026-05")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r20);

            FaithProcessRecord r21 = FaithProcessRecord.builder()
                    .church(churchMap.get("도쿄교회"))
                    .yearMonth("2026-06")
                    .evangReg(373)
                    .bibleMonthReg(10)
                    .bibleCumReg(17)
                    .bibleCurAtt(21)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(382)
                    .yearStartReg(382)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(4)
                    .attReg(373)
                    .attOnsite(58)
                    .attOnline(92)
                    .attEtc(175)
                    .attTotal(325)
                    .absOnce(26)
                    .absLongManage(0)
                    .absLongUnmanage(22)
                    .absTotal(48)
                    .build();
            faithProcessRecordRepository.save(r21);

            FaithProcessRecord r22 = FaithProcessRecord.builder()
                    .church(churchMap.get("텍사스교회"))
                    .yearMonth("2026-06")
                    .evangReg(138)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(17)
                    .centerCumOff(0)
                    .centerCumReg(17)
                    .centerMonthGrad(5)
                    .centerTotMonthReg(45)
                    .centerCumGrad(5)
                    .centerAttElem(48)
                    .centerAttMid(23)
                    .centerAttHigh(12)
                    .registered(138)
                    .yearStartReg(138)
                    .regChange(0)
                    .newAdmit(5)
                    .cumNewAdmit(5)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(138)
                    .attOnsite(2)
                    .attOnline(36)
                    .attEtc(85)
                    .attTotal(123)
                    .absOnce(0)
                    .absLongManage(15)
                    .absLongUnmanage(0)
                    .absTotal(15)
                    .build();
            faithProcessRecordRepository.save(r22);

            FaithProcessRecord r23 = FaithProcessRecord.builder()
                    .church(churchMap.get("튀르키예교회"))
                    .yearMonth("2026-06")
                    .evangReg(961)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(57)
                    .centerMonthTotal(57)
                    .centerCumOn(0)
                    .centerCumOff(127)
                    .centerCumReg(127)
                    .centerMonthGrad(12)
                    .centerTotMonthReg(46)
                    .centerCumGrad(32)
                    .centerAttElem(50)
                    .centerAttMid(50)
                    .centerAttHigh(36)
                    .registered(964)
                    .yearStartReg(964)
                    .regChange(0)
                    .newAdmit(12)
                    .cumNewAdmit(32)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(20)
                    .attReg(961)
                    .attOnsite(99)
                    .attOnline(248)
                    .attEtc(452)
                    .attTotal(799)
                    .absOnce(15)
                    .absLongManage(122)
                    .absLongUnmanage(25)
                    .absTotal(162)
                    .build();
            faithProcessRecordRepository.save(r23);

            FaithProcessRecord r24 = FaithProcessRecord.builder()
                    .church(churchMap.get("파키스탄교회"))
                    .yearMonth("2026-06")
                    .evangReg(2687)
                    .bibleMonthReg(0)
                    .bibleCumReg(47)
                    .bibleCurAtt(0)
                    .centerMonthOn(78)
                    .centerMonthOff(90)
                    .centerMonthTotal(168)
                    .centerCumOn(78)
                    .centerCumOff(168)
                    .centerCumReg(246)
                    .centerMonthGrad(33)
                    .centerTotMonthReg(96)
                    .centerCumGrad(97)
                    .centerAttElem(84)
                    .centerAttMid(59)
                    .centerAttHigh(45)
                    .registered(2692)
                    .yearStartReg(2692)
                    .regChange(0)
                    .newAdmit(33)
                    .cumNewAdmit(97)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(64)
                    .attReg(2687)
                    .attOnsite(635)
                    .attOnline(469)
                    .attEtc(1165)
                    .attTotal(2269)
                    .absOnce(40)
                    .absLongManage(70)
                    .absLongUnmanage(308)
                    .absTotal(418)
                    .build();
            faithProcessRecordRepository.save(r24);

            FaithProcessRecord r25 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이교회"))
                    .yearMonth("2026-06")
                    .evangReg(71)
                    .bibleMonthReg(146)
                    .bibleCumReg(146)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(71)
                    .yearStartReg(71)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(71)
                    .attOnsite(5)
                    .attOnline(51)
                    .attEtc(9)
                    .attTotal(65)
                    .absOnce(0)
                    .absLongManage(4)
                    .absLongUnmanage(2)
                    .absTotal(6)
                    .build();
            faithProcessRecordRepository.save(r25);

            FaithProcessRecord r26 = FaithProcessRecord.builder()
                    .church(churchMap.get("콩고민주공화국킨샤사교회"))
                    .yearMonth("2026-06")
                    .evangReg(1756)
                    .bibleMonthReg(101)
                    .bibleCumReg(241)
                    .bibleCurAtt(234)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(1756)
                    .yearStartReg(1756)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(32)
                    .attReg(1756)
                    .attOnsite(836)
                    .attOnline(201)
                    .attEtc(464)
                    .attTotal(1501)
                    .absOnce(68)
                    .absLongManage(178)
                    .absLongUnmanage(9)
                    .absTotal(255)
                    .build();
            faithProcessRecordRepository.save(r26);

            FaithProcessRecord r27 = FaithProcessRecord.builder()
                    .church(churchMap.get("대전교회카자흐스탄아스타나지역"))
                    .yearMonth("2026-06")
                    .evangReg(86)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(6)
                    .centerCumReg(6)
                    .centerMonthGrad(8)
                    .centerTotMonthReg(12)
                    .centerCumGrad(8)
                    .centerAttElem(15)
                    .centerAttMid(14)
                    .centerAttHigh(10)
                    .registered(86)
                    .yearStartReg(86)
                    .regChange(0)
                    .newAdmit(8)
                    .cumNewAdmit(8)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(86)
                    .attOnsite(8)
                    .attOnline(19)
                    .attEtc(50)
                    .attTotal(77)
                    .absOnce(9)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(9)
                    .build();
            faithProcessRecordRepository.save(r27);

            FaithProcessRecord r28 = FaithProcessRecord.builder()
                    .church(churchMap.get("대전교회포르투갈리스본지역"))
                    .yearMonth("2026-06")
                    .evangReg(91)
                    .bibleMonthReg(0)
                    .bibleCumReg(10)
                    .bibleCurAtt(35)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(91)
                    .yearStartReg(91)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(91)
                    .attOnsite(23)
                    .attOnline(20)
                    .attEtc(34)
                    .attTotal(77)
                    .absOnce(4)
                    .absLongManage(10)
                    .absLongUnmanage(0)
                    .absTotal(14)
                    .build();
            faithProcessRecordRepository.save(r28);

            FaithProcessRecord r29 = FaithProcessRecord.builder()
                    .church(churchMap.get("천안교회멕시코과달라하라지역"))
                    .yearMonth("2026-06")
                    .evangReg(200)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(2)
                    .centerTotMonthReg(12)
                    .centerCumGrad(2)
                    .centerAttElem(12)
                    .centerAttMid(12)
                    .centerAttHigh(7)
                    .registered(200)
                    .yearStartReg(200)
                    .regChange(0)
                    .newAdmit(2)
                    .cumNewAdmit(2)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(200)
                    .attOnsite(12)
                    .attOnline(172)
                    .attEtc(0)
                    .attTotal(184)
                    .absOnce(11)
                    .absLongManage(5)
                    .absLongUnmanage(0)
                    .absTotal(16)
                    .build();
            faithProcessRecordRepository.save(r29);

            FaithProcessRecord r30 = FaithProcessRecord.builder()
                    .church(churchMap.get("청주교회브라질리우데자네이루지역"))
                    .yearMonth("2026-06")
                    .evangReg(336)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(92)
                    .centerMonthTotal(90)
                    .centerCumOn(0)
                    .centerCumOff(92)
                    .centerCumReg(90)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(336)
                    .yearStartReg(336)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(27)
                    .attReg(336)
                    .attOnsite(7)
                    .attOnline(256)
                    .attEtc(21)
                    .attTotal(284)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(52)
                    .absTotal(52)
                    .build();
            faithProcessRecordRepository.save(r30);

            FaithProcessRecord r31 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이교회인도네시아마카사르지역"))
                    .yearMonth("2026-06")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r31);

            FaithProcessRecord r32 = FaithProcessRecord.builder()
                    .church(churchMap.get("대전교회해외개척지역"))
                    .yearMonth("2026-06")
                    .evangReg(133)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(27)
                    .centerCumReg(27)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(133)
                    .yearStartReg(133)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(133)
                    .attOnsite(58)
                    .attOnline(55)
                    .attEtc(18)
                    .attTotal(131)
                    .absOnce(0)
                    .absLongManage(2)
                    .absLongUnmanage(0)
                    .absTotal(2)
                    .build();
            faithProcessRecordRepository.save(r32);

            FaithProcessRecord r33 = FaithProcessRecord.builder()
                    .church(churchMap.get("청주교회해외개척지역"))
                    .yearMonth("2026-06")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r33);

            FaithProcessRecord r34 = FaithProcessRecord.builder()
                    .church(churchMap.get("텍사스교회해외개척지역"))
                    .yearMonth("2026-06")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(20)
                    .centerMonthTotal(20)
                    .centerCumOn(0)
                    .centerCumOff(20)
                    .centerCumReg(20)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r34);

            FaithProcessRecord r35 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이교회해외개척지역"))
                    .yearMonth("2026-06")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r35);

            FaithProcessRecord r36 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이인도하이데라바드지역"))
                    .yearMonth("2026-06")
                    .evangReg(2494)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(2494)
                    .yearStartReg(2494)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(2494)
                    .attOnsite(743)
                    .attOnline(747)
                    .attEtc(505)
                    .attTotal(1995)
                    .absOnce(170)
                    .absLongManage(149)
                    .absLongUnmanage(180)
                    .absTotal(499)
                    .build();
            faithProcessRecordRepository.save(r36);

            FaithProcessRecord r37 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이인도뭄바이지역"))
                    .yearMonth("2026-06")
                    .evangReg(723)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(723)
                    .yearStartReg(723)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(723)
                    .attOnsite(245)
                    .attOnline(175)
                    .attEtc(133)
                    .attTotal(553)
                    .absOnce(6)
                    .absLongManage(164)
                    .absLongUnmanage(0)
                    .absTotal(170)
                    .build();
            faithProcessRecordRepository.save(r37);

            FaithProcessRecord r38 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이인도오디샤지역"))
                    .yearMonth("2026-06")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r38);

            FaithProcessRecord r39 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이인도카르나타카서부지역"))
                    .yearMonth("2026-06")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r39);

            FaithProcessRecord r40 = FaithProcessRecord.builder()
                    .church(churchMap.get("텍사스교회부에아지역"))
                    .yearMonth("2026-06")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(0)
                    .centerMonthOff(0)
                    .centerMonthTotal(0)
                    .centerCumOn(0)
                    .centerCumOff(0)
                    .centerCumReg(0)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r40);

            FaithProcessRecord r41 = FaithProcessRecord.builder()
                    .church(churchMap.get("인도첸나이교회인도네시아쿠팡지역"))
                    .yearMonth("2026-06")
                    .evangReg(0)
                    .bibleMonthReg(0)
                    .bibleCumReg(0)
                    .bibleCurAtt(0)
                    .centerMonthOn(28)
                    .centerMonthOff(0)
                    .centerMonthTotal(28)
                    .centerCumOn(28)
                    .centerCumOff(0)
                    .centerCumReg(28)
                    .centerMonthGrad(0)
                    .centerTotMonthReg(0)
                    .centerCumGrad(0)
                    .centerAttElem(0)
                    .centerAttMid(0)
                    .centerAttHigh(0)
                    .registered(0)
                    .yearStartReg(0)
                    .regChange(0)
                    .newAdmit(0)
                    .cumNewAdmit(0)
                    .discipline(0)
                    .cumDiscipline(0)
                    .moveIn(0)
                    .moveOut(0)
                    .transIn(0)
                    .transOut(0)
                    .dupReg(0)
                    .prevNewAdmitCnt(0)
                    .attReg(0)
                    .attOnsite(0)
                    .attOnline(0)
                    .attEtc(0)
                    .attTotal(0)
                    .absOnce(0)
                    .absLongManage(0)
                    .absLongUnmanage(0)
                    .absTotal(0)
                    .build();
            faithProcessRecordRepository.save(r41);

            log.info("Successfully seeded all 21 churches and 42 faith process records into PostgreSQL database!");
        }
    }
}
